logger:
  enabled: false
dump_server:
  host: example.com
  user: anonymizer
  port: 22
  passphrase:
  path: /path/to/dumps/directory
database:
  user: root
  host: 127.0.0.1
  pass: anonymizer
tmp_path: /tmp
cap:
  ssh_options:
    keys: 
      - /path/to/private/ssh/key/for/deployment